### ISSUE TITLE
Error with Krypton nightlies - debug attached - help appreciated

### ISSUE THREAD

**Issue by gigantaur** [andybotting/xbmc-addon-abc-iview#1401]
Hi Andy,

I am trying to get your fantastic addon to work with the krypton nightlies (in essence my wife won't let me run Krypton without it!). 

I have tried 1.6.7 and manually installed 1.6.8.  It browses to channels/genres and then gives an error.

Debug is [here](http://xbmclogs.com/py6ztncpz) - refer line 1222 roughly.

cheers,
gigantaur

**Comment by andybotting** [comment]
Hi @gigantaur 

I've had a couple of other reports about this. I *think* it's due to SSL verification, and it seems to be mostly on Apple platforms (Mac, AppleTV).

I've just pushed a change to disable verification completely. Can you try the latest master zip file?
https://github.com/andybotting/xbmc-addon-abc-iview/archive/master.zip

cheers

**Comment by gigantaur** [comment]
Works.  Awesome.  Thanks for getting to so quickly.

I did read in context of SR that there is an urrlib issue - might be relevant  - I spent hours trying to solve/follow the hints and even did a dedicated python using brew with no luck 
https://github.com/SickRage/SickRage/wiki/SSL-Errors

Perhaps an option to disable ssl verification if can't be fixed ?

**Comment by andybotting** [comment]
Nice summary in that link. I've not had any issues with SickRage, but I think that might be because the Linux distros just make it work.

I have a feeling that ABC might be using SSL only for trying to obfuscate URLs used by the iView app from being sniffed on the network, so I'm tempted to just disable SSL verification completely. No personal/private information is sent here - it's basically just a public API.

If you can confirm that the fix in b8df2459c6179db04c6b4b112080ec3ef16a9307 works for you, then I'll push it to the repo.

**Comment by gigantaur** [comment]
Works well. Great stuff.

Will it be 1.6.9 ?  Which repo should I get it from ? (I have never been able to find the latest through normal kodi sanctioned repos so have used the zip manually)

**Comment by andybotting** [comment]
You'll want to use our own XBMC Catchup TV AU repository. It's definitely
the recommended way to install iView. You'll get automatic updates and
dependency installation.

See the readme listed here:
https://github.com/xbmc-catchuptv-au/repo

**Comment by gigantaur** [comment]
Thanks.  Repo fails to load .. I'll post on issues there.
