### ISSUE TITLE
Crash on specific episodes on Android Kodi

### ISSUE THREAD

**Issue by sudsy** [andybotting/xbmc-addon-abc-iview#223]
Certain episodes cause Kodi to crash on Android when using the iView plugin. I am unable to determine if this bug is related to your plugin or the Kodi core. Here is the crash log.

 http://xbmclogs.com/prpyputie

The video I used to cause the crash is available on iView at 

http://iview.abc.net.au/programs/tashi/CH1261H038S00

Kodi on Windows doesn't cause this crash. 

If the video that caused the crash is no longer available by the time you read this, the following video also causes a crash. The crash is caused in the first couple of minutes.

http://iview.abc.net.au/programs/tashi/CH1261H028S00

**Comment by andybotting** [comment]
Thanks for an excellent bug report! I watched that episode fine with Kodi on Linux. I see you're using the Nexus Player - looks like it's an x86 device with Android - that's probably a fairly new device. 

Generally, issues like these are not caused by the addons. The iView addon only does enough to get access to the video stream and Kodi does the rest.

Have you tried Gotham on this device?

**Comment by andybotting** [comment]
Looks like it works fine on Kodi Android ARM too

**Comment by sudsy** [comment]
Thanks for checking that. That really helps narrow it down. I should report it as a bug for Nexus Player only and in relation to the CDVDPlayer module.

I haven't had a chance to run gotham on this box to test it. I keep intending to but run out of time. I am going to submit this as is to the bugtracker for Kodi and then try to get some more information about whether it is working on gotham or not in the coming days. I want to make sure that the files that make it crash are still available.
